name: Build and Test Microservices

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore ./src

      - name: Build Solutions
        run: dotnet build ./src --no-restore

      - name: Run Unit and Integration Tests
        run: dotnet test ./src --no-build --verbosity normal